# Generated by Django 5.0.3 on 2024-06-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sports/'),
        ),
    ]
